name: envoy-gateway
title: Envoy Gateway
type: infrastructure
icon: envoy
scalable: false

helm:
  name: envoy-gateway
  source: oci://docker.io/envoyproxy/gateway-helm
  chart: oci://docker.io/envoyproxy/gateway-helm
  version: 1.7.2

workloads:
- name: main
  kind: deployment
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{helm.release}}'
      app.kubernetes.io/name: gateway-helm
  primary: true
  helm:
    annotations: deployment.pod.annotations
    labels: deployment.pod.labels
  containers:
  - name: envoy-gateway
    helm:
      resources: deployment.envoyGateway.resources
