name: envoy-gateway
title: Envoy Gateway
type: infrastructure
icon: envoy
scalable: false

helm:
  name: envoy-gateway
  source: oci://docker.io/envoyproxy/gateway-helm
  chart: oci://docker.io/envoyproxy/gateway-helm
  version: v1.8.2
  crdCharts:
  - name: envoy-gateway-crds
    source: oci://docker.io/envoyproxy/gateway-crds-helm
    chart: oci://docker.io/envoyproxy/gateway-crds-helm
    version: v1.8.2
    values:
    - name: crds.gatewayAPI.enabled
      value: true
    - name: crds.gatewayAPI.channel
      value: experimental
    - name: crds.envoyGateway.enabled
      value: true
  values:
  - name: crds.enabled
    value: false

workloads:
- name: main
  kind: deployment
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{helm.release}}'
      app.kubernetes.io/name: gateway-helm
  primary: true
  helm:
    annotations: deployment.pod.annotations
    labels: deployment.pod.labels
  containers:
  - name: envoy-gateway
    helm:
      resources: deployment.envoyGateway.resources
